### PR TITLE
[WIP] Sort on field Insert

### PR DESCRIPTION
**Pull request by ajnsit**
Keeping the fields sorted would make inserts and lookups O(log n), and would make duplicate checks easy. There is almost definitely more work that would need to be done, but I'm opening this PR to get an idea if this is a direction we want to go in.

### CODE REVIEW

**Comment by neongreen** [comment]
I don't see how it will make lookups O(log n) — you have no way to random-access a type-level list. Runtime lookups are O(1) already.

**Comment by neongreen** [comment]
You can get O(log n) compile-time lookups by using a type-level binary tree: https://hackage.haskell.org/package/type-level-bst-0.1. This will add a huge amount of complexity. We are unlikely to do it in jrec.

**Comment by ajnsit** [comment]
I meant compile time performance, since this is type level. But you are right, it might not be possible to get `log n` lookups with a straight list. Having a sorted list of fields could be beneficial for things like diffing records and removing duplicates (if those are to be added to jrec at some point).

**Comment by neongreen** [comment]
Yeah, for detecting duplicates when merging two records a sorted list is better.

This might be added eventually, but it's a lot of work — much more than a single type family — so I'll close the PR for now.

**Pull request closed without merging**
